### ISSUE TITLE
On creating new Run Configuration, set not correct Environment Variables

### ISSUE THREAD

**Issue by EarlJester** [rafaelldi/aspire-plugin#114]
In latest versions, is impossible to start using plugin without normalize Environment Variables
Logs have no errors or detailed information. All looks like work fine
Additionaly need to fix Build Project to Build Solution

![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/0c02c6f2-57c1-40ba-a98a-25b70c2f96b3)

![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/786cc204-ff0d-4849-b1d3-7e7d7aee7aff)

For plugin users, look #109 for information how to fix this problem.

**Comment by rafaelldi** [comment]
Something seems to have happened to your run configuration template. Could you check if this is reproducible on the new Aspire template project? 
To fix this, you can go to the `.idea` folder, find the `workspace.xml` file there, copy it to another location to backup it and remove from the `AutoGeneratedRunConfigurationManager` a line with the `kind="AspireHost"` and from the `RunManager` all configurations with type `AspireHostConfiguration`. After that, all Aspire run configurations will be deleted and Rider will generate a new one from the `launchSettings.json` file.

**Comment by ondrejpialek** [comment]
Some of my observations, hopefully not redundant. I was cleaning up some env variables (as part of the migration to .NET Aspire preview 5) and was actually confused by a couple of things.

1) When I added env vars through the IDE (Edit Run configuration), those were not written to `launchSettings.json`, which confused me
2) When I manually edited `launchSettings.json` those changes appear in the IDE Run configuration (was surprising to me given the above). But these changes are NOT applied when the configuration is run.
3) `workspace.xml` had some old random url to run the dashboard on. It did not pick up when I changed the `applicationUrl` from `launchSettings.json`. When I hit Run in Rider it launched the dashboard on this old URL, whereas `dotnet run` used the correct URL from `launchSettings.json`
4) Edit Run configuration in Rider also shows `ASPNETCORE_URLS` env variable, with the value of `applicationUrl` from `launchSettings.json`, even when this env variable is not explicitly set (might be expected, but is confusing).
5) In `workspace.xml` there is no `applicationUrl` anywhere, but the value is stored as `ASPNETCORE_URLS`, which is what makes me believe that this is expected. But in my `workspace.xml` this still had the old value (identical to what is set in the `browser` element)
6) Only when I manually changed an env value from the GUI (Edit Run configuration) the section under `workspace.xml` was regenerated and my manual changes made in `launchSettings.json` were picked up, including the URLs and other random env settings

**Comment by rafaelldi** [comment]
Thank you for such a detailed review!

All this happens because `launchSettings.json` is the standard way for Visual Studio to serialize and store run configurations. All JetBrains IDEs use a different way and a different format. The plugin automatically creates a run configuration from the `launchSettings.json` file to speed things up, and also tries to update the created run configuration if there are any changes in the `launchSettings.json` file. But it doesn't save changes from the run configuration to the `launchSettings.json` file, because they might be undesirable (and conceptually they are different things). It also stops synchronizing changes if there are changes in the run configuration that are not in the `launchSettings.json` file, to avoid conflicting situations.
So, the preferred ways are to make changes to the `launchSettings.json` file (then they will be synced with the run configuration) or to make changes in the UI only (they will not be saved to the `launchSettings.json` file, but you can save the run configuration as a project file and share it with your colleagues if needed).

I understand that this can be confusing and we are discussing how it can be improved. But first of all, it should be implemented in Rider itself and only then in the plugin.
I hope that after the stable release of Aspire and the plugin, there won't be so many breaking changes and you won't need to change anything in the run configuration.

**Comment by EarlJester** [comment]
@rafaelldi Yes, its IDE `Aspire Host default="true" `configuration was corrupted. Right -- before cleanup, left --after.
![image](https://github.com/rafaelldi/aspire-plugin/assets/111294669/6d1b4aaa-a8e4-47a3-8c44-eb201e8052e2)
