### ISSUE TITLE
0.6.1 prevents dashboard access

### ISSUE THREAD

**Issue by yoDon** [rafaelldi/aspire-plugin#139]
After upgrading to the Rider Aspire Plugin 0.6.1, I'm unable to access the Aspire dashboard when launching via Rider using the Aspire Plugin configurations for either AppHost http or AppHost https.

I'm now encountering an "Enter token to login" dashboard screen I've never seen before, and, critically, when I look in the console logs I no longer see the console message that used to be there, telling me the login token url (which I'd previously not needed to use).

This change happened when I upgraded my plugin version.

The dashboard works as expected when launching the AppHost via dotnet run or in Rider using the non-Asipire-Plugin AppHost http launch config.

**Comment by rafaelldi** [comment]
What do you have in the console log view? This is not part of the plugin, the Aspire Host project should write this log to the console with the correct link after startup.

<img width="975" alt="image" src="https://github.com/rafaelldi/aspire-plugin/assets/16965141/f12848e7-fae0-4556-9064-bca132350558">

Could you also check what is in the `.idea\.idea.{Your solution name}\.idea\workspace.xml` file. There should be a `RunManager` section there with a similar configuration (sometimes it can be corrupted due to changes in aspire).

```xml
<configuration name="AspireApp.AppHost" type="AspireHostConfiguration" factoryName="Aspire Host" activateToolWindowBeforeRun="false">
  <option name="PROJECT_FILE_PATH" value="$PROJECT_DIR$/AspireApp/AspireApp.AppHost/AspireApp.AppHost.csproj" />
  <option name="LAUNCH_PROFILE_NAME" value="http" />
  <option name="TRACK_ENVS" value="1" />
  <envs>
    <env name="DOTNET_ENVIRONMENT" value="Development" />
    <env name="ASPNETCORE_ENVIRONMENT" value="Development" />
    <env name="DOTNET_DASHBOARD_OTLP_ENDPOINT_URL" value="http://localhost:19253" />
    <env name="DOTNET_RESOURCE_SERVICE_ENDPOINT_URL" value="http://localhost:20176" />
    <env name="ASPNETCORE_URLS" value="http://localhost:15064" />
    <env name="DOTNET_LAUNCH_PROFILE" value="http" />
  </envs>
  <option name="TRACK_URL" value="1" />
  <browser url="http://localhost:15064/login?t=947c36ef-9b11-4db1-a2ce-036503d686c8" start="true" />
  <method v="2">
    <option name="Build Solution" enabled="true" />
  </method>
</configuration>
```

**Comment by yoDon** [comment]
I believe this was cause by a mismatch of preview aspire versions 5 & 6, and dotnet aspire workload versions. After cleaning that version mess up the plugin seems to be working as expected. That's for checking on this.
