### ISSUE TITLE
Restart a specific project doesn't reconnect it to the host dashboard

### ISSUE THREAD

**Issue by JohnGalt1717** [rafaelldi/aspire-plugin#72]
If I hit restart on the debug output window for a given project that is attached to the host it doesn't reconnect properly in the dashboard etc. I'm not sure if this is aspire or this plugin.

**Comment by rafaelldi** [comment]
Hi! This wasn't a feature of the plugin. The restart button was available because the run configurations were used underneath. After #74, I changed the project launch mechanism, so the restart button should no longer be there. 
I may add a restart mechanism in the future (if it is useful in any cases), but first I need to check if Aspire supports project restarts.

**Comment by JohnGalt1717** [comment]
It's unfortunate that this isn't fully baked yet. My understanding is that it's coming in vs.net and vs code for beta 4 because rerunning the whole thing is ridiculous just because you made one change in one microservice. I understand your approach given the reality at the moment however.
